version: 1.0.{build}
image: Visual Studio 2017
install:
- choco install resharper-clt
- choco install opencover.portable
- choco install codecov
before_build:
- ps: nuget restore
build:
  verbosity: minimal
after_build:
- InspectCode.exe -o=resharper-clt-output.xml FluentHelium.sln
- ps: $result = [xml](Get-Content .\resharper-clt-output.xml)
- ps: $result.Report.Issues.ChildNodes | % {$project = $_.Name; $_.ChildNodes | % {Add-AppveyorCompilationMessage -Message $_.Message -Line $_.Line -FileName $_.File -ProjectName $project}}
test_script:
- OpenCover.Console.exe -register:user -target:"C:/Program Files/dotnet/dotnet.exe" -targetargs:"test --no-build FluentHelium.Tests.sln" -output:".\FluentHelium.Coverage.xml" -oldstyle
- codecov -f "FluentHelium.Coverage.xml"